CREATE TABLE IF NOT EXISTS auth_session (
  token TEXT PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_auth_session_user
  ON auth_session(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_session_expiry
  ON auth_session(expires_at);

CREATE TABLE IF NOT EXISTS auth_session_revocation (
  user_id INTEGER NOT NULL,
  token TEXT NOT NULL,
  revoked_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (user_id, token)
);

CREATE TABLE IF NOT EXISTS auth_session_legacy_block (
  user_id INTEGER PRIMARY KEY NOT NULL,
  blocked_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS app_state (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_counter (
  kind TEXT NOT NULL,
  day TEXT NOT NULL,
  value INTEGER DEFAULT 0 NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (kind, day)
);

CREATE TABLE IF NOT EXISTS app_cache (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
